name: NexoWar
version: 1.0-SNAPSHOT
main: me.nexo.war.NexoWar
api-version: '1.21'
depend: [NexoCore, NexoClans, NexoEconomy, NexoProtections]
commands:
  war:
    description: Comando principal del sistema de Guerras de Honor.
    aliases: [guerra]
    permission: nexowar.user
    permission-message: "No tienes permiso para usar este comando."
