name: NexoDungeons
version: '1.0'
main: me.nexo.dungeons.NexoDungeons
description: 'Motor Híbrido de Mazmorras y Puzzles Data-Driven.'
author: 'Z0101'
# 🌟 FIX: Aplicado el estándar exacto de la documentación
api-version: '26.1.2'

dependencies:
  server:
    # 📌 DEPENDENCIAS FUERTES (Obligatorias para el motor de mazmorras)
    NexoCore:
      load: BEFORE
      required: true
      join-classpath: true
    NexoEconomy:
      load: BEFORE
      required: true
      join-classpath: true
    FastAsyncWorldEdit:
      load: BEFORE
      required: false
      join-classpath: true
    MythicMobs:
      load: BEFORE
      required: false
      join-classpath: true

# 💡 NOTA: Los comandos /dungeons han sido delegados al código Java (Lamp)