# ==========================================
# 🏛️ Nexo Network - Arquitectura Enterprise
# Manifiesto Clásico Bukkit/Spigot/Paper
# ==========================================

name: NexoDungeons
version: '${version}'
main: me.nexo.dungeons.NexoDungeons
api-version: '1.21'
description: 'Motor Híbrido de Mazmorras y Puzzles Data-Driven.'
authors: [Z0101]

# 🚀 SISTEMA DE DEPENDENCIAS CLÁSICO
depend: [NexoCore, NexoEconomy]
softdepend: [MythicMobs, FastAsyncWorldEdit]

# 📚 PERMISOS (Integración Nativa con LuckPerms)
permissions:
  nexodungeons.user:
    description: 'Permite abrir el menú principal de Nexo Dungeons.'
    default: true