name: NexoEconomy
version: '1.0-SNAPSHOT'
main: me.nexo.economy.NexoEconomy
description: 'Motor de economía, intercambios y mercado global.'
author: 'Z0101'
api-version: '26.1.2'

dependencies:
  server:
    NexoCore:
      required: true
      join-classpath: true
    NexoItems:
      required: true
      join-classpath: true