# ==========================================
# 🏛️ Nexo Network - Arquitectura Enterprise
# Manifiesto Clásico Bukkit/Spigot/Paper
# ==========================================

name: NexoEconomy
version: '${version}'
main: me.nexo.economy.NexoEconomy
api-version: '1.21'
description: 'Motor Financiero Global, Bazar y Mercado Clandestino.'

# 🚀 SISTEMA DE DEPENDENCIAS CLÁSICO
depend: [NexoCore, NexoItems]

# 📚 PERMISOS NATIVOS (Integración con LuckPerms)
permissions:
  nexoeconomy.user:
    description: 'Permite el acceso a los comandos básicos de economía, bazar y trade.'
    default: true
  nexoeconomy.admin:
    description: 'Permite emitir fondos, alterar cuentas y abrir el mercado negro remotamente.'
    default: op