name: NexoClans
version: '${project.version}'
main: me.nexo.clans.NexoClans
api-version: '1.21'
author: 'Z0101'
description: 'Motor de progresión cooperativa y clanes.'
depend: [NexoCore , NexoEconomy]
commands:
  clan:
    description: Comando principal de clanes
  c:
    description: Chat privado del clan
    permission: nexoclans.chat
    permission-message: "&#8b0000[!] No puedes usar el chat de clan si no perteneces a uno."