# ==========================================
# 🏛️ Nexo Network - Arquitectura Enterprise
# Manifiesto Clásico Bukkit/Spigot/Paper
# ==========================================

name: NexoClans
version: '${version}'
main: me.nexo.clans.NexoClans
api-version: '1.21'
authors: [Z0101]
description: 'Motor de progresión cooperativa y clanes.'

# 🚀 SISTEMA DE DEPENDENCIAS CLÁSICO
depend: [NexoCore, NexoEconomy]

# 📚 PERMISOS (Integración Nativa LuckPerms)
permissions:
  nexoclans.chat:
    description: 'Permite el uso del chat privado del clan.'
    default: true