name: NexoMechanics
version: '${project.version}'
main: me.nexo.mechanics.NexoMechanics
api-version: '1.21'
author: 'TuNombre'
description: 'Mecanicas adicionales y minijuegos.'
depend: [NexoCore, NexoEconomy]
softdepend: [NexoProtections]

commands:
  skilltree:
    description: Abre el árbol de habilidades.
    permission: nexomechanics.user
    permission-message: "No tienes permiso para usar este comando."
