name: NexoColecciones
version: '1.0-SNAPSHOT'
main: me.nexo.colecciones.NexoColecciones
description: 'Sistema de Slayers y farmeo progresivo.'
author: 'Z0101'
api-version: '26.1.2'

dependencies:
  server:
    NexoCore:
      required: true
      join-classpath: true
    NexoEconomy:
      required: false
      join-classpath: true