# ==========================================
# 🏛️ Nexo Network - Arquitectura Enterprise
# Manifiesto Clásico Bukkit/Spigot/Paper
# ==========================================

name: NexoItems
version: '${version}'
main: me.nexo.items.NexoItems
api-version: '1.21'
description: 'Manejador de armaduras, armas, mochilas y accesorios.'

# 🚀 SISTEMA DE DEPENDENCIAS CLÁSICO
depend: [NexoCore, Nexo]

# 📚 PERMISOS NATIVOS (Integración con LuckPerms)
permissions:
  nexoitems.user:
    description: 'Permite el acceso a menús de usuario como desguace, accesorios, pv, forja y wardrobe.'
    default: true
  nexo.admin:
    description: 'Permite el uso de herramientas de testeo de desarrollador.'
    default: op