name: NexoPvP
version: '${project.version}'
main: me.nexo.pvp.NexoPvP
api-version: '1.21'
author: 'TuNombre'
description: 'Sistema de combate y pasivas PvP.'
depend: [NexoCore, NexoProtections, NexoEconomy]
softdepend: [NexoWar]

# 📚 DICCIONARIO GLOBAL DE PERMISOS (Para LuckPerms)
permissions:
  nexopvp.user:
    description: Permite activar o desactivar el modo PvP.
    default: true # 'true' hace que los usuarios normales ya lo tengan

  nexopvp.templo:
    description: Permite abrir el menú del templo de bendiciones.
    default: true

  nexopvp.admin:
    description: Permisos administrativos del módulo PvP.
    default: op # Solo los OP (operadores) lo tienen por defecto