name: NexoFactories
version: 1.0-SNAPSHOT
main: me.nexo.factories.NexoFactories
api-version: '1.21'
depend: [NexoCore, NexoProtections]
softdepend: [NexoItems]

commands:
  factory:
    description: Comandos para la gestión de fábricas.
    permission: nexofactories.user
    permission-message: "No tienes permiso para usar este comando."
