# ==========================================
# 🏛️ Nexo Network - Arquitectura Enterprise
# Manifiesto Nativo Paper 1.21.5+
# ==========================================

name: NexoCore
version: '${version}'
main: me.nexo.core.NexoCore
api-version: '1.21'
description: 'Cerebro principal y conexion a base de datos de la red Nexo.'
authors:
  - 'Z0101'

# 🚀 SISTEMA DE DEPENDENCIAS MODERNO (Paper)
dependencies:
  server:
    # --- Dependencias Obligatorias (depend) ---
    AuraSkills:
      load: BEFORE
      required: true
    Nexo:
      load: BEFORE
      required: true

    # 🌟 FIX CRÍTICO APLICADO: NexoEconomy eliminado para romper el bucle infinito

    # --- Dependencias Opcionales (softdepend) ---
    PlaceholderAPI:
      load: BEFORE
      required: false
    MythicMobs:
      load: BEFORE
      required: false
    eco:
      load: BEFORE
      required: false
    floodgate:
      load: BEFORE
      required: false


# 🗄️ LIBRERÍAS DE TIEMPO DE EJECUCIÓN (Zero-Bloat)
libraries:
  - com.zaxxer:HikariCP:5.1.0
  - org.postgresql:postgresql:42.7.2
  - com.github.ben-manes.caffeine:caffeine:3.1.8