name: NexoCore
version: '1.0-SNAPSHOT'
main: me.nexo.core.NexoCore
description: 'Cerebro principal y conexion a base de datos de la red Nexo.'
author: 'Z0101'
api-version: '26.1.2'

dependencies:
  server:
    AuraSkills:
      required: true
      join-classpath: true
    Nexo:
      required: true
      join-classpath: true
    PlaceholderAPI:
      required: false
      join-classpath: true